name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment-pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
