name: Deployment pipeline

env:
  DEPLOYMENT_SKIPPED: ${{ github.event_name != 'push' || contains(join(github.event.commits.*.message) , '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment-pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ env.DEPLOYMENT_SKIPPED == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Deployment success notification
        if: success()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          text: Deployment succeeded!
          details: head commit ${{github.event.head_commit.url}}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Deployment failure notification
        if: failure()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: failure
          text: Deployment failed!
          details: head commit ${{github.event.head_commit.url}}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}

  tag-release:
    needs: [deployment-pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.DEPLOYMENT_SKIPPED == 'false' }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
