name: Deployment pipeline

env:
  DEPLOYMENT_SKIPPED: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message) , '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment-pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ env.DEPLOYMENT_SKIPPED == true }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag-release:
    needs: [deployment-pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.DEPLOYMENT_SKIPPED == true }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
